# Generated by Django 2.2.6 on 2019-11-18 18:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('alias', models.CharField(max_length=40)),
                ('avatar', models.ImageField(blank=True, default='/media/profile/e2.png', upload_to='profile')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_official', models.BooleanField(default=False)),
                ('is_advertiser', models.BooleanField(default=False)),
                ('company', models.CharField(default='', max_length=100)),
                ('balance', models.FloatField(default=0)),
                ('sex', models.BooleanField(default=True)),
                ('age', models.DateField(blank=True, default=datetime.datetime.now)),
                ('IDCard', models.FileField(blank=True, upload_to='IDcards')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('name', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('version', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('IMG', models.ImageField(blank=True, default='', upload_to='post')),
                ('IsModerated', models.BooleanField(default=False)),
                ('IsAdvert', models.BooleanField(default=False)),
                ('IsInlinePost', models.BooleanField(default=False)),
                ('AdURL', models.URLField(blank=True, default='', max_length=250)),
                ('AppearenceFrequency', models.IntegerField(default=1)),
                ('NumberOfLikes', models.IntegerField(default=0)),
                ('IsActive', models.BooleanField(default=True)),
                ('CampaignTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('IsPublic', models.BooleanField(default=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertSettings',
            fields=[
                ('admin', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('AdFrequency', models.IntegerField(default=50)),
                ('MoneyForSeen', models.FloatField(default=0)),
                ('MoneyForClick', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TimeLine',
            fields=[
                ('date', models.DateField(auto_now_add=True)),
                ('content_post', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Post')),
                ('post_from_last_advert', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('IMG', models.ImageField(blank=True, upload_to='template')),
                ('ID', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('IsPublic', models.BooleanField(default=False)),
                ('type', models.CharField(default='portrait', max_length=100)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('template', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Template')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostLabelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Label')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Post')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalScoringProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=1)),
                ('label', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Label')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='score', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MimeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='/media/profile/e2.png', upload_to='profile')),
                ('IsAdvertiser', models.BooleanField(default=False)),
                ('company', models.CharField(default='', max_length=100)),
                ('balance', models.FloatField(default=0)),
                ('sex', models.BooleanField(default=True)),
                ('age', models.DateField(blank=True, default=datetime.datetime.now)),
                ('IsOfficial', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemeContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMG', models.ImageField(blank=True, upload_to='post')),
                ('index', models.IntegerField(default=0)),
                ('post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='api.Post')),
                ('template', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Template')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='channel', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('ID', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('NumberOfLikes', models.IntegerField(default=0)),
                ('post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Post')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('None', 'None'), ('Like', 'Like'), ('View', 'View'), ('Click', 'Click'), ('Favourite', 'Favourite')], max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
