# Generated by Django 2.2.6 on 2019-11-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='IsAdult',
            field=models.BooleanField(default=False),
        ),
    ]
