# Generated by Django 2.2.6 on 2019-11-21 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_isadult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='NumberOfLikes',
        ),
    ]
