# Generated by Django 2.2.6 on 2019-12-01 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_searchresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Post'),
        ),
    ]
