# Generated by Django 2.2.6 on 2019-10-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191014_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='AdURL',
            field=models.URLField(blank=True, default='', max_length=250),
        ),
    ]
