# Generated by Django 2.2.6 on 2019-12-01 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191201_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Post'),
        ),
    ]
