# Generated by Django 2.2.6 on 2019-12-01 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191201_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='result',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Post'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
