# Generated by Django 2.2.6 on 2019-12-04 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_commentlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='CampaignTime',
        ),
        migrations.AddField(
            model_name='post',
            name='CampaignTimeend',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='post',
            name='CampaignTimestart',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
