# Generated by Django 2.2.6 on 2019-12-05 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_post_popularityscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='PopularityScore',
        ),
    ]
