# Generated by Django 2.2.6 on 2019-10-16 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_advertsettings_mimeuser_timeline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MimeUser',
        ),
    ]
