# Generated by Django 2.2.6 on 2019-12-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_post_popularityscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='PopularityScore',
            field=models.IntegerField(default=0),
        ),
    ]
