# Generated by Django 2.2.6 on 2019-12-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_post_popularityscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='PopularityScore',
        ),
        migrations.AddField(
            model_name='post',
            name='popularityscore',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
