# Generated by Django 2.2.6 on 2019-12-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191205_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='popularityscore',
            field=models.IntegerField(default=0),
        ),
    ]
