# Generated by Django 2.2.6 on 2019-12-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20191206_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='popularityscore',
        ),
    ]
