# Generated by Django 2.2.6 on 2019-10-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20191018_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='IsActive',
            field=models.BooleanField(default=True),
        ),
    ]
