# Generated by Django 2.2.6 on 2019-12-06 23:18

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_post_popularityscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='memecontent',
            name='type',
            field=models.CharField(default='portrait', max_length=100),
        ),
        migrations.AlterField(
            model_name='memecontent',
            name='IMG',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='IMG',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='', upload_to='post'),
        ),
        migrations.AlterField(
            model_name='template',
            name='IMG',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='template'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='/media/profile/e2.png', upload_to='profile'),
        ),
        migrations.CreateModel(
            name='MemeText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Post')),
            ],
        ),
    ]
