# Generated by Django 2.2.6 on 2019-12-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20191206_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='complete_account',
            field=models.BooleanField(default=True),
        ),
    ]
