# Generated by Django 2.2.6 on 2019-10-23 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
