# Generated by Django 2.2.6 on 2019-12-09 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_user_complete_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='template',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
