# Generated by Django 2.2.6 on 2019-12-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20191209_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='DarkMode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
