# Generated by Django 2.2.6 on 2019-10-25 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_label_memecontent_personalscoringprofile_postlabelling_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlabelling',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Label'),
        ),
        migrations.AlterField(
            model_name='postlabelling',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Post'),
        ),
    ]
