# Generated by Django 2.2.6 on 2019-10-26 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20191026_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memecontent',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='api.Post'),
        ),
    ]
