# Generated by Django 2.2.6 on 2019-10-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20191031_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mimeuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/media/profile/e2.png', upload_to='profile'),
        ),
    ]
