# Generated by Django 2.2.6 on 2019-11-09 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_post_ispublic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='CampaignTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
