# Generated by Django 2.2.6 on 2019-11-11 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20191109_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='mimeuser',
            name='age',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
