# Generated by Django 2.2.6 on 2019-11-15 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_recycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='memecontent',
            name='template',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Template'),
        ),
    ]
