# Generated by Django 2.2.6 on 2019-10-14 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='URL',
            new_name='AdURL',
        ),
    ]
