# Generated by Django 2.2.6 on 2019-10-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('None', 'None'), ('Like', 'Like'), ('View', 'View'), ('Click', 'Click')], max_length=100),
        ),
    ]
