# Generated by Django 2.2.6 on 2019-10-25 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('name', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MemeContent',
            fields=[
                ('IMG', models.ImageField(blank=True, upload_to='post')),
                ('index', models.IntegerField(default=0)),
                ('post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('IMG', models.ImageField(blank=True, upload_to='template')),
                ('ID', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('IsPublic', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostLabelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Label')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Post')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalScoringProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=1)),
                ('label', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Label', unique=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
