# Generated by Django 2.2.6 on 2019-10-26 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20191025_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalscoringprofile',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='score', to=settings.AUTH_USER_MODEL),
        ),
    ]
