# Generated by Django 2.2.6 on 2019-10-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20191026_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memecontent',
            name='id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
    ]
