# Generated by Django 2.2.6 on 2019-10-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20191031_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mimeuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', upload_to='profile'),
        ),
    ]
