# Generated by Django 2.2.6 on 2019-11-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_memecontent_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='type',
            field=models.CharField(default='portrait', max_length=100),
        ),
    ]
